### ISSUE TITLE
Fetch Project Details Dynamically from GitHub API

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#177]
### Description:
Currently, the project information displayed on `/projects` is hardcoded in the HTML template. We want to dynamically fetch project information from the GitHub API to ensure the page stays updated with the latest information.

### Requirements:
1. **Environment Variables**: 
   - The project names will be provided via environment variables.
   - Example: `PROJECT_NAMES="project1,project2,project3"`

2. **Fetch Public Repositories**:
   - Use the GitHub API to fetch details of repositories from the ContriHUB organization.
   - Match the project names (from environment variables) with the names of the public repositories in ContriHUB.

3. **Pull Information**:
   - For each matching repository, retrieve the following details:
     1. **Project Name**.
     2. **Maintainer**: The username of the repo owner or collaborator.
     3. **About**: The description (about) section of the repository.

4. **Dynamic Rendering**:
   - Update the Django view to fetch the project data dynamically and pass it to the template.
   - Modify the HTML template to display this dynamically fetched data.

### Tasks:
- [ ] Read project names from environment variables.
- [ ] Use GitHub API to fetch details of matching repositories.
- [ ] Extract relevant information: name, maintainer, and about section.
- [ ] Update the `/projects` page to display fetched data dynamically.

**Comment by samimshoaib01** [comment]
Can i get help on this :
![image](https://github.com/user-attachments/assets/c4a85e90-9fa1-4d66-8bd5-555fac70e375)

**Comment by meisabhishekpatel** [comment]
@samimshoaib01 try to access http:// not https://
Also if you are using google chrome try using Firefox, also turn off upgrade secure connection option from settings

**Comment by samimshoaib01** [comment]
Do, I need to match the design 0f previous one  or it will be new issue:
![image](https://github.com/user-attachments/assets/db9d6572-69df-4d3f-b2f1-763f4511ec32)

**Comment by samimshoaib01** [comment]
@meisabhishekpatel 
kindly respond sir

**Comment by meisabhishekpatel** [comment]
@samimshoaib01 ofcourse you need to manage the old design, you need to change in the existing code, not create a new page from scratch .

**Comment by hexwhiz** [comment]
@meisabhishekpatel whenever I open the local server using http://127.0.0.1:8000 it shows this
![image](https://github.com/user-attachments/assets/9194be2c-7b38-48e1-bdc2-1c6599667d44)

I tried using different browsers and disable secure connection option. But still the http changes to https in the browser. Can you help me with this?

**Comment by meisabhishekpatel** [comment]
@hexwhiz try incognito or firefox with secure connection off

**Comment by hexwhiz** [comment]
@meisabhishekpatel there are some things I want to ask.
- From the API fetch request, I get the details of all the repos. So, to get the mentor of a repo, I am using `repo['parent']['login']` which is basically the GitHub username of the account from where the repos is forked to @contrihub. So, should I just display the usernames directly or fetch the name of the mentor with separate API request? It might exceed GitHub API limit.
- Also, there are projects that don't have a parent owner. Take this one for example. This repo is not forked from your account, so I don't get your username in my return object. How should I handle that

**Comment by meisabhishekpatel** [comment]
@hexwhiz 
1. username is just fine no need to fetch the exact name.
2.  there will be only one such project only in contrihub which is Contrihub-24 for that you can get name of maintainer from env only  since the maintainer which change each year.

Also I would like to clarify that do always make API call each time I hit /project instead store the project information in database and new project should be added when I hit populate issues end points then only.

**Comment by hexwhiz** [comment]
@meisabhishekpatel PR submitted. And it somehow shows "Review required" with red color. Should I be worried about that?

**Comment by meisabhishekpatel** [comment]
@hexwhiz no that protect which we have added in the repo so that without proper review and approval, we can not  merge the PR.

**Comment by DeshDeepakKushwaha** [comment]
I would love to work on this issue

**Comment by DeshDeepakKushwaha** [comment]
Is The Issue free now ?

**Comment by lokesh-wagh** [comment]
issue gets solved by another PR
